source 'https://github.com/CocoaPods/Specs.git'

project 'LightUUp.xcodeproj'

# Uncomment this line to define a global platform for your project
platform :ios, '10.0'

target 'LightUUp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LightUUp
  pod 'Interpolate', '~> 0.3'
end
